### ISSUE TITLE
Better stack trace

### ISSUE THREAD

**Issue by Christilut** [express-promise-router/express-promise-router#59]
I'm not sure this is the right place to ask this but maybe I can be pointed in the right direction.

If my code throws an error, I get this almost entirely useless stack trace and I would love a better trace:
```
  "stack": "APIError: test error\n    at new ExtendableError 
(/home/user/workspace/test-api/server/helpers/error.ts:25:11)\n    at new APIError 
(/home/user/workspace/test-api/server/helpers/error.ts:41:5)\n
    at app.use (/home/user/workspace/test-api/config/express.ts:112:24)\n
    at Layer.handle_error (/home/user/workspace/test-api/node_modules/express/lib/router/layer.js:71:5)\n
    at trim_prefix (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:315:13)\n    at /home/user/workspace/test-api/node_modules/express/lib/router/index.js:284:7\n
    at Function.process_params (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:335:12)\n
    at next (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:275:10)\n
    at Layer.handle_error (/home/user/workspace/test-api/node_modules/express/lib/router/layer.js:67:12)\n
    at trim_prefix (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:315:13)\n
    at /home/user/workspace/test-api/node_modules/express/lib/router/index.js:284:7\n
    at Function.process_params (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:335:12)\n
    at next (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:275:10)\n 
    at Layer.handle_error (/home/user/workspace/test-api/node_modules/express/lib/router/layer.js:67:12)\n
    at trim_prefix (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:315:13)\n 
    at /home/user/workspace/test-api/node_modules/express/lib/router/index.js:284:7\n
    at Function.process_params (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:335:12)\n 
   at next (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:275:10)\n 
   at /home/user/workspace/test-api/node_modules/express/lib/router/index.js:635:15\n
   at Immediate.next (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:260:14)\n
   at Immediate.<anonymous> (/home/user/workspace/test-api/node_modules/express/lib/router/index.js:635:15)\n 
   at runCallback (timers.js:812:20)\n 
   at tryOnImmediate (timers.js:768:5)\n
   at processImmediate [as _immediateCallback] (timers.js:745:5)",
```

Is there any way to do this or anywhere I should look for more information on this?

**Comment by mormahr** [comment]
`express-promise-router` really has nothing to do with error handling in express, or did you notice any difference between the unpatched express router and the promisified one? It's probably the best idea to ask on stackoverflow. Otherwise your question should be directed at express directly.

**Comment by Christilut** [comment]
Thanks, you're right. I'll try stackoverflow
